import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";


import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


const interFont = Inter({
  subsets: ["latin"],
  weight: ["100", "300", "700"],
})

const poppinFont = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "700"],
})
// Local Fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nike UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add Helvetica Neue CDN */}
        <link
          rel="stylesheet"
          href="https://fonts.cdnfonts.com/css/helvetica-neue"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ fontFamily: "'Helvetica Neue', Arial, sans-serif" }} // Apply Helvetica Neue
      >
        {children}
      </body>
    </html>
  );
}
